name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and test CI_macOS
      working-directory: ./EssentialFeed
      run: xcodebuild clean build test -scheme CI_macOS
    - name: Build and test CI_iOS
      run: xcodebuild clean build test -scheme CI_iOS

